export const dealTestData = {
  items: [
    {
      _id: "62e2f1b6e59bc496629bef7b",
      guarantors: [
        {
          firstName: "Victor",
          lastName: "Pajonas",
          phoneNumber: "Pajonas",
          emailAddress: "vp@flatironrealtycapital.com",
          estimatedCreditScore: "700-719",
          percentageEntityOwnership: "100",
        },
      ],
      subjectProperties: [
        {
          address: {
            streetNumber: "1234",
            streetName: "Broadway",
            city: "New York",
            state: "NY",
            country: "USA",
            zip: "10001",
          },
          purchasePrice: 500000,
          purchaseDate: "2019-05-21T04:00:00.000Z",
          propertyWillBeVacant: "false",
          hardRenovationCosts: 40000,
          softRenovationCosts: 1000,
          totalRehabBudget: 41000,
          totalSquareFootage: 35,
          postRenovationValue: 124337,
          postRenovationSquareFootage: 33,
          annualPropertyTaxes: 123,
          annualPropertyInsurance: 123,
          annualFloodInsurance: 123,
          annualHomeownersAssociationFees: 213,
          annualPropertyManagementFees: 123,
          subjectPropertyType: "2 unit",
          units: [
            {
              unit: 1,
              unitOccupied: "No",
              leaseType: "Month-to-Month",
              unitSquareFootage: 15,
              bedroomCount: 1,
              bathroomCount: 1,
              unitMonthlyInPlaceRent: 2000,
              unitMonthlyMarketRent: 2000,
              expectedStabilizedRent: 2000,
              leaseBeginDate: "2019-05-21T04:00:00.000Z",
              leaseEndDate: "2019-05-21T04:00:00.000Z",
              lease: [],
            },
            {
              unit: 2,
              unitOccupied: "No",
              leaseType: "Month-to-Month",
              unitSquareFootage: 16,
              bedroomCount: 1,
              bathroomCount: 1,
              unitMonthlyInPlaceRent: 2000,
              unitMonthlyMarketRent: 2000,
              expectedStabilizedRent: 2000,
              leaseBeginDate: "2019-05-21T04:00:00.000Z",
              leaseEndDate: "2019-05-21T04:00:00.000Z",
            },
          ],
        },
        {
          address: {
            streetNumber: "555",
            streetName: "Madison Avenue",
            city: "New York",
            state: "NY",
            country: "USA",
            zip: "United States",
          },
          purchasePrice: 2131,
          purchaseDate: null,
          propertyWillBeVacant: "false",
          hardRenovationCosts: 213,
          softRenovationCosts: 123,
          totalRehabBudget: 123,
          totalSquareFootage: 123,
          postRenovationValue: 123,
          postRenovationSquareFootage: 213,
          annualPropertyTaxes: 231,
          annualPropertyInsurance: 213,
          annualFloodInsurance: 213,
          annualHomeownersAssociationFees: 123,
          annualPropertyManagementFees: 213,
          subjectPropertyType: "SFR",
          units: [
            {
              unit: "0",
              unitOccupied: "Yes",
              leaseType: "Short-term (vacation rental, AirBnB or VRBO)",
              unitSquareFootage: 10,
              bedroomCount: 1,
              bathroomCount: 1,
              unitMonthlyInPlaceRent: 13,
              unitMonthlyMarketRent: 13,
              expectedStabilizedRent: 13,
              leaseBeginDate: "2019-05-21T04:00:00.000Z",
              leaseEndDate: "2019-05-21T04:00:00.000Z",
              lease: [],
            },
          ],
        },
      ],
      currentUserIsGurantor: "Yes",
      loanProductType: "30-Year Rental Loan",
      loanPurpose: "Purchase",
      loanPropertyHasMoreThanFourUnits: "false",
      applicationIsForMultipleProperties: "Multiple",
      numberOfSubjectProperties: 2,
      hasWorkedWithFlatironInPast: "false",
      requestedLoanAmount: 600000,
      totalRentInPlace: 13,
      totalMarketRent: 13,
      totalStablizedMarketRent: 13,
      formType: "createDeal",
      submissionDate: "07/28/2022",
      submitted: true,
      createdBy: "vp@flatironrealtycapital.com",
      submittedBy: "vp@flatironrealtycapital.com",
      owners: [],
      unknown: "02f403f6-0eb4-11ed-ade5-2f93864bad73.png",
      readPermission: [],
      writePermission: [],
      borrowers: [
        {
          _id: "62cc6b1577e9d1193e32ebf2",
          firstName: "Jimmyyyy",
          lastName: "Oliva",
          emailAddress: "jo@flatironrealtycapital.com",
          phoneNumber: "6314563373",
          formType: "creditAuth",
          userType: "admin",
          verified: true,
          borrower: { blobs: { photoId: "62cd8c7a039c49d20a14e43a" } },
          blobs: { signature: "62cd8c7a039c49d20a14e43b" },
          $set: {},
        },
        {
          _id: "62dea5e4b49ad62e203657ba",
          firstName: "Victor",
          lastName: "Pajonas",
          emailAddress: "vp@flatironrealtycapital.com",
          phoneNumber: "5164916464",
          formType: "creditAuth",
          userType: "borrower",
          verified: true,
          borrower: { blobs: { photoId: "62def7daf933f8965c7062bb" } },
          blobs: { signature: "62def7daf933f8965c7062bc" },
          id: 2,
          passport: "112f6e2c-129c-11ed-ade5-2f93864bad73.png",
          unkownDocs: [],
        },
      ],
    },
  ],
};
