export const dummyLeadGenEntitySearch = [
  {
    entity_results_page: "b2ea2cc9e90e4bb492b3b19238940e84",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "b2ea2cc9e90e4bb492b3b19238940e84",
    company_entity_id: "C2__LTEwOTI0NDgzMDA3NQ",
    result_entity_name: "MOKE PEACE PEACE PEACE CORP.",
    name_match_score: 98,
    relevance_score: 50,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "127-21 LIBERTY AVENUE",
      City: "RICHMOND HILL",
      State: "NY",
      ZipCode: "11419",
      County: "QUEENS COUNTY",
      Country: "UNITED STATES",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
    source_references: "Corporate Filing",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: null,
    incorporated_date: null,
    sum_of_scores: 150,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "b2ea2cc9e90e4bb492b3b19238940e84",
      company_entity_id: "C2__LTEwOTI0NDgzMDA3NQ",
      pulled_business_name: "MOKE PEACE PEACE PEACE CORP.",
      name_match_score: 98,
      relevance_score: 50,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "127-21 LIBERTY AVENUE",
        City: "RICHMOND HILL",
        State: "NY",
        ZipCode: "11419",
        County: "QUEENS COUNTY",
        Country: "UNITED STATES",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
      full_result: {
        GroupId: "b2ea2cc9e90e4bb492b3b19238940e84",
        RecordCount: "1",
        Relevance: "50",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE PEACE PEACE CORP.",
            Address: {
              Street: "127-21 LIBERTY AVENUE",
              City: "RICHMOND HILL",
              State: "NY",
              ZipCode: "11419",
              Country: "UNITED STATES",
            },
            FileState: "NY",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE PEACE PEACE CORP.",
            Address: {
              Street: "127-21 LIBERTY AVENUE",
              City: "RICHMOND HILL",
              State: "NY",
              ZipCode: "11419",
              County: "QUEENS COUNTY",
              Country: "UNITED STATES",
            },
            Phones: {},
            ListOfFileStates: {
              FileState: "NY",
            },
            CorporationInfo: {
              CorporationNumber: "4555687",
              StateOfIncorporation: "NEW YORK",
            },
            Message:
              "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
            CompanyEntityId: "C2__LTEwOTI0NDgzMDA3NQ",
            AllSourceDocuments: {
              SourceName: "Corporate Filing",
              SourceDocumentGuid: "I90213b12bcbb11e398db8b09b4f043e0",
            },
          },
        },
      },
      business_address_street: "127-21 LIBERTY AVENUE",
      business_address_city: "RICHMOND HILL",
      business_address_state: "NY",
      business_address_zip: "11419",
      source_references: "Corporate Filing",
      incorporated_state: "NEW YORK",
      source_includes_corp_filing: 1,
    },
    business_address_street: "127-21 LIBERTY AVENUE",
    business_address_city: "RICHMOND HILL",
    business_address_state: "NY",
    business_address_zip: "11419",
  },
  {
    entity_results_page: "e2ac0a9706544053b43d7772145963fc",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "e2ac0a9706544053b43d7772145963fc",
    company_entity_id: "C2__LTEwNzEyMTExMjA2NA",
    result_entity_name: "MOKE PEACE 11 CORP.",
    name_match_score: 70,
    relevance_score: 44,
    count_of_sources_for_entity: 4,
    returned_business_address: {
      Street: "1202 HALSEY STREET",
      City: "BROOKLYN",
      State: "NEW YORK",
      ZipCode: "11207",
      County: "KINGS COUNTY",
      Country: "UNITED STATES",
      Latitude: "40.691364",
      Longitude: "-73.909684",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
    source_references: "UCC, Corporate Filing, Worldbase, UCC",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: [
      {
        Name: "Example Name 1",
        Title: "PRESIDENT",
      },
      {
        Name: "MICHAEL KANDHOROV",
        Title: "PRESIDENT",
      },
      {
        Name: "Example Name 3",
        Title: "PRESIDENT",
      },
    ],
    incorporated_date: "2015",
    sum_of_scores: 119,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "e2ac0a9706544053b43d7772145963fc",
      company_entity_id: "C2__LTEwNzEyMTExMjA2NA",
      pulled_business_name: "MOKE PEACE 11 CORP.",
      name_match_score: 70,
      relevance_score: 44,
      count_of_sources_for_entity: 4,
      returned_business_address: {
        Street: "1202 HALSEY STREET",
        City: "BROOKLYN",
        State: "NEW YORK",
        ZipCode: "11207",
        County: "KINGS COUNTY",
        Country: "UNITED STATES",
        Latitude: "40.691364",
        Longitude: "-73.909684",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
      full_result: {
        GroupId: "e2ac0a9706544053b43d7772145963fc",
        RecordCount: "4",
        Relevance: "44",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 11 CORP.",
            Address: {
              Street: "1202 HALSEY STREET",
              City: "BROOKLYN",
              State: "NEW YORK",
              ZipCode: "11207",
              Country: "UNITED STATES",
            },
            FileState: "NY",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 11 CORP.",
            Address: {
              Street: "1202 HALSEY STREET",
              City: "BROOKLYN",
              State: "NEW YORK",
              ZipCode: "11207",
              County: "KINGS COUNTY",
              Country: "UNITED STATES",
              Latitude: "40.691364",
              Longitude: "-73.909684",
            },
            AlternateAddresses: {
              Street: "1202 HALSEY ST",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11207-2679",
              County: "KINGS COUNTY",
              Country: "USA",
              Latitude: "40.691364",
              Longitude: "-73.909684",
            },
            Phones: {},
            BusinessExecutives: {
              Name: "MICHAEL KANDHOROV",
              Title: "PRESIDENT",
            },
            ListOfDUNSNumbers: {
              DUNSNumber: "07-983-8257",
            },
            ListOfFileStates: {
              FileState: "NY",
            },
            CorporationInfo: [
              {
                CorporationNumber: "4793258",
                StateOfIncorporation: "NEW YORK",
              },
              {
                DateIncorporated: "2015",
              },
            ],
            UCCInfo: [
              {
                UCCFilingDate: "09/10/2020",
              },
              {
                UCCFilingDate: "07/22/2015",
              },
            ],
            Message:
              "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
            CompanyEntityId: "C2__LTEwNzEyMTExMjA2NA",
            AllSourceDocuments: [
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I4d2432e0553f11eaadfea82903531a62",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I8fd7b0b132cd11e598dc8b09b4f043e0",
              },
              {
                SourceName: "Worldbase",
                SourceDocumentGuid: "Ia88bb0a0b76f11e8a5b3e3d9e23d7429",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I07138980f4aa11eabea4f0dc9fb69570",
              },
            ],
          },
        },
      },
      business_address_street: "1202 HALSEY STREET",
      business_address_city: "BROOKLYN",
      business_address_state: "NEW YORK",
      business_address_zip: "11207",
      source_references: "UCC, Corporate Filing, Worldbase, UCC",
      incorporated_state: "NEW YORK",
      incorporated_date: "2015",
      source_includes_corp_filing: 1,
      business_executives: [
        {
          Name: "MICHAEL KANDHOROV",
          Title: "PRESIDENT",
        },
      ],
    },
    business_address_street: "1202 HALSEY STREET",
    business_address_city: "BROOKLYN",
    business_address_state: "NEW YORK",
    business_address_zip: "11207",
  },
  {
    entity_results_page: "a2559553439b4fc0a191b37e99891c1d",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "a2559553439b4fc0a191b37e99891c1d",
    company_entity_id: "C2__LTEwOTI1MzU5Njk0Nw",
    result_entity_name: "MOKE PEACE 19 CORP.",
    name_match_score: 70,
    relevance_score: 44,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "90 STATE STREET",
      City: "ALBANY",
      State: "NY",
      ZipCode: "12207",
      County: "ALBANY COUNTY",
      Country: "UNITED STATES",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
    source_references: "Corporate Filing",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: null,
    incorporated_date: null,
    sum_of_scores: 116,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "a2559553439b4fc0a191b37e99891c1d",
      company_entity_id: "C2__LTEwOTI1MzU5Njk0Nw",
      pulled_business_name: "MOKE PEACE 19 CORP.",
      name_match_score: 70,
      relevance_score: 44,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "90 STATE STREET",
        City: "ALBANY",
        State: "NY",
        ZipCode: "12207",
        County: "ALBANY COUNTY",
        Country: "UNITED STATES",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
      full_result: {
        GroupId: "a2559553439b4fc0a191b37e99891c1d",
        RecordCount: "1",
        Relevance: "44",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 19 CORP.",
            Address: {
              Street: "90 STATE STREET",
              StreetLine2: "STE 700, OFFICE 40",
              City: "ALBANY",
              State: "NY",
              ZipCode: "12207",
              Country: "UNITED STATES",
            },
            FileState: "NY",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 19 CORP.",
            Address: {
              Street: "90 STATE STREET",
              City: "ALBANY",
              State: "NY",
              ZipCode: "12207",
              County: "ALBANY COUNTY",
              Country: "UNITED STATES",
            },
            Phones: {},
            ListOfFileStates: {
              FileState: "NY",
            },
            CorporationInfo: {
              CorporationNumber: "4980700",
              StateOfIncorporation: "NEW YORK",
            },
            Message:
              "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
            CompanyEntityId: "C2__LTEwOTI1MzU5Njk0Nw",
            AllSourceDocuments: {
              SourceName: "Corporate Filing",
              SourceDocumentGuid: "I19a2863350f511e698dc8b09b4f043e0",
            },
          },
        },
      },
      business_address_street: "90 STATE STREET",
      business_address_city: "ALBANY",
      business_address_state: "NY",
      business_address_zip: "12207",
      source_references: "Corporate Filing",
      incorporated_state: "NEW YORK",
      source_includes_corp_filing: 1,
    },
    business_address_street: "90 STATE STREET",
    business_address_city: "ALBANY",
    business_address_state: "NY",
    business_address_zip: "12207",
  },
  {
    entity_results_page: "b3e025da4a6548ff844e400cc92762a8",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "b3e025da4a6548ff844e400cc92762a8",
    company_entity_id: "C2__LTExNTg5NDM5Mzg1OA",
    result_entity_name: "MOKE PEACE 43 CORP",
    name_match_score: 71,
    relevance_score: 44,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "280 ETNA ST",
      City: "BROOKLYN",
      State: "NY",
      ZipCode: "11208-1634",
      County: "KINGS COUNTY",
      Country: "USA",
      Latitude: "40.686841",
      Longitude: "-73.873562",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Worldbase",
    source_references: "Worldbase",
    incorporated_state: null,
    source_includes_corp_filing: -1,
    business_executives: [
      {
        Name: "THOMAS SHEENAN",
        Title: "PRESIDENT",
      },
    ],
    incorporated_date: null,
    sum_of_scores: 115,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "b3e025da4a6548ff844e400cc92762a8",
      company_entity_id: "C2__LTExNTg5NDM5Mzg1OA",
      pulled_business_name: "MOKE PEACE 43 CORP",
      name_match_score: 71,
      relevance_score: 44,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "280 ETNA ST",
        City: "BROOKLYN",
        State: "NY",
        ZipCode: "11208-1634",
        County: "KINGS COUNTY",
        Country: "USA",
        Latitude: "40.686841",
        Longitude: "-73.873562",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Worldbase",
      full_result: {
        GroupId: "b3e025da4a6548ff844e400cc92762a8",
        RecordCount: "1",
        Relevance: "44",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 43 CORP",
            Address: {
              Street: "280 ETNA ST",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11208-1634",
              Country: "USA",
            },
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 43 CORP",
            Address: {
              Street: "280 ETNA ST",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11208-1634",
              County: "KINGS COUNTY",
              Country: "USA",
              Latitude: "40.686841",
              Longitude: "-73.873562",
            },
            Phones: {},
            SICDetail: {
              SICCode: "9999",
              SICDesc: "Nonclassifiable Establishments",
            },
            BusinessExecutives: {
              Name: "THOMAS SHEENAN",
              Title: "PRESIDENT",
            },
            ListOfDUNSNumbers: {
              DUNSNumber: "08-068-4183",
            },
            ListOfFileStates: {},
            Message:
              "Please Note: Limited information is available for this business. Information is included from Worldbase",
            CompanyEntityId: "C2__LTExNTg5NDM5Mzg1OA",
            AllSourceDocuments: {
              SourceName: "Worldbase",
              SourceDocumentGuid: "I9627d5608ff211e79bef99c0ee06c731",
            },
          },
        },
      },
      business_address_street: "280 ETNA ST",
      business_address_city: "BROOKLYN",
      business_address_state: "NY",
      business_address_zip: "11208-1634",
      source_references: "Worldbase",
      source_includes_corp_filing: -1,
      business_executives: [
        {
          Name: "THOMAS SHEENAN",
          Title: "PRESIDENT",
        },
      ],
    },
    business_address_street: "280 ETNA ST",
    business_address_city: "BROOKLYN",
    business_address_state: "NY",
    business_address_zip: "11208-1634",
  },
  {
    entity_results_page: "b1105d65006d450bb59b9eedf58fae80",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "b1105d65006d450bb59b9eedf58fae80",
    company_entity_id: "C2__LTExODk5NTE5Nzg3MQ",
    result_entity_name: "MOKE PEACE 18 CORP",
    name_match_score: 71,
    relevance_score: 44,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "736 EAST 86TH STREET",
      City: "BROOKLYN",
      State: "NY",
      ZipCode: "11234",
      County: "KINGS COUNTY",
      Country: "UNITED STATES",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
    source_references: "Corporate Filing",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: [
      {
        Name: "FRANK EMEKA",
        Title: "TITLE NOT AVAILABLE",
      },
    ],
    incorporated_date: "03/11/2017",
    sum_of_scores: 117,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "b1105d65006d450bb59b9eedf58fae80",
      company_entity_id: "C2__LTExODk5NTE5Nzg3MQ",
      pulled_business_name: "MOKE PEACE 18 CORP",
      name_match_score: 71,
      relevance_score: 44,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "736 EAST 86TH STREET",
        City: "BROOKLYN",
        State: "NY",
        ZipCode: "11234",
        County: "KINGS COUNTY",
        Country: "UNITED STATES",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
      full_result: {
        GroupId: "b1105d65006d450bb59b9eedf58fae80",
        RecordCount: "1",
        Relevance: "44",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 18 CORP",
            Address: {
              Street: "736 EAST 86TH STREET",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11234",
              Country: "UNITED STATES",
            },
            FileState: "CT",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 18 CORP",
            Address: {
              Street: "736 EAST 86TH STREET",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11234",
              County: "KINGS COUNTY",
              Country: "UNITED STATES",
            },
            Phones: {},
            BusinessExecutives: {
              Name: "FRANK EMEKA",
              Title: "TITLE NOT AVAILABLE",
            },
            ListOfFileStates: {
              FileState: "CT",
            },
            CorporationInfo: {
              CorporationNumber: "1232648",
              StateOfIncorporation: "NEW YORK",
              DateIncorporated: "03/11/2017",
            },
            Message:
              "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
            CompanyEntityId: "C2__LTExODk5NTE5Nzg3MQ",
            AllSourceDocuments: {
              SourceName: "Corporate Filing",
              SourceDocumentGuid: "I704adcd01e5411e798dc8b09b4f043e0",
            },
          },
        },
      },
      business_address_street: "736 EAST 86TH STREET",
      business_address_city: "BROOKLYN",
      business_address_state: "NY",
      business_address_zip: "11234",
      source_references: "Corporate Filing",
      incorporated_state: "NEW YORK",
      incorporated_date: "03/11/2017",
      source_includes_corp_filing: 1,
      business_executives: [
        {
          Name: "FRANK EMEKA",
          Title: "TITLE NOT AVAILABLE",
        },
      ],
    },
    business_address_street: "736 EAST 86TH STREET",
    business_address_city: "BROOKLYN",
    business_address_state: "NY",
    business_address_zip: "11234",
  },
  {
    entity_results_page: "dac0a225338b4d4b80e77f6830f3ca9b",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "dac0a225338b4d4b80e77f6830f3ca9b",
    company_entity_id: "C2__LTc0MTExMjUwODUw",
    result_entity_name: "MOKE PEACE 18 CORP",
    name_match_score: 71,
    relevance_score: 44,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "736 E 86TH ST",
      City: "BROOKLYN",
      State: "NY",
      ZipCode: "11236",
      County: "KINGS COUNTY",
      Country: "UNITED STATES",
      Latitude: "40.63918",
      Longitude: "-73.90979",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from ",
    source_references: "Business Phone",
    incorporated_state: null,
    source_includes_corp_filing: -1,
    business_executives: [
      {
        Name: "FRANCES EMEKA",
        Title: "PRESIDENT",
      },
    ],
    incorporated_date: null,
    sum_of_scores: 115,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "dac0a225338b4d4b80e77f6830f3ca9b",
      company_entity_id: "C2__LTc0MTExMjUwODUw",
      pulled_business_name: "MOKE PEACE 18 CORP",
      name_match_score: 71,
      relevance_score: 44,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "736 E 86TH ST",
        City: "BROOKLYN",
        State: "NY",
        ZipCode: "11236",
        County: "KINGS COUNTY",
        Country: "UNITED STATES",
        Latitude: "40.63918",
        Longitude: "-73.90979",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from ",
      full_result: {
        GroupId: "dac0a225338b4d4b80e77f6830f3ca9b",
        RecordCount: "1",
        Relevance: "44",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 18 CORP",
            Address: {
              Street: "736 E 86TH ST",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11236",
              Country: "UNITED STATES",
            },
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 18 CORP",
            Address: {
              Street: "736 E 86TH ST",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11236",
              County: "KINGS COUNTY",
              Country: "UNITED STATES",
              Latitude: "40.63918",
              Longitude: "-73.90979",
            },
            Phones: {
              PhoneNumber: "(718) 000-1111",
            },
            BusinessExecutives: {
              Name: "FRANCES EMEKA",
              Title: "PRESIDENT",
            },
            ListOfFileStates: {},
            Message:
              "Please Note: Limited information is available for this business. Information is included from ",
            CompanyEntityId: "C2__LTc0MTExMjUwODUw",
            AllSourceDocuments: {
              SourceName: "Business Phone",
              SourceDocumentGuid: "Iafb74ec1115111e9a5b3e3d9e23d7429",
            },
          },
        },
      },
      business_address_street: "736 E 86TH ST",
      business_address_city: "BROOKLYN",
      business_address_state: "NY",
      business_address_zip: "11236",
      source_references: "Business Phone",
      source_includes_corp_filing: -1,
      business_executives: [
        {
          Name: "FRANCES EMEKA",
          Title: "PRESIDENT",
        },
      ],
    },
    business_address_street: "736 E 86TH ST",
    business_address_city: "BROOKLYN",
    business_address_state: "NY",
    business_address_zip: "11236",
  },
  {
    entity_results_page: "9916fbe0b1844448b0ef1894d9327ce7",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "9916fbe0b1844448b0ef1894d9327ce7",
    company_entity_id: "C2__LTExMjYzMDU4NzQ1NQ",
    result_entity_name: "MOKE PEACE CORP.",
    name_match_score: 70,
    relevance_score: 43,
    count_of_sources_for_entity: 22,
    returned_business_address: {
      Street: "127-21 LIBERTY AVENUE",
      City: "RICHMOND HILL",
      State: "NEW YORK",
      ZipCode: "11419",
      County: "QUEENS COUNTY",
      Country: "UNITED STATES",
      Latitude: "40.688736",
      Longitude: "-73.817784",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
    source_references:
      "UCC, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Worldbase, UCC, UCC, UCC, UCC, UCC, UCC, UCC",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: [
      {
        Name: "SHAHMINA A AKTHER",
        Title: "PRINCIPAL",
      },
    ],
    incorporated_date: null,
    sum_of_scores: 136,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "9916fbe0b1844448b0ef1894d9327ce7",
      company_entity_id: "C2__LTExMjYzMDU4NzQ1NQ",
      pulled_business_name: "MOKE PEACE CORP.",
      name_match_score: 70,
      relevance_score: 43,
      count_of_sources_for_entity: 22,
      returned_business_address: {
        Street: "127-21 LIBERTY AVENUE",
        City: "RICHMOND HILL",
        State: "NEW YORK",
        ZipCode: "11419",
        County: "QUEENS COUNTY",
        Country: "UNITED STATES",
        Latitude: "40.688736",
        Longitude: "-73.817784",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
      full_result: {
        GroupId: "9916fbe0b1844448b0ef1894d9327ce7",
        RecordCount: "22",
        Relevance: "43",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE CORP.",
            Address: {
              Street: "127-21 LIBERTY AVENUE",
              City: "RICHMOND HILL",
              State: "NEW YORK",
              ZipCode: "11419",
              Country: "UNITED STATES",
            },
            FileState: "NY",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE CORP.",
            Address: {
              Street: "127-21 LIBERTY AVENUE",
              City: "RICHMOND HILL",
              State: "NEW YORK",
              ZipCode: "11419",
              County: "QUEENS COUNTY",
              Country: "UNITED STATES",
              Latitude: "40.688736",
              Longitude: "-73.817784",
            },
            AlternateBusinessNames: {
              BusinessName: [
                "MOKE PEACE 71 CORP.",
                "MOKE PEACE 31 CORP.",
                "MOKE PEACE 25 CORP.",
                "MOKE PEACE 63 CORP.",
                "MOKE PEACE 26 CORP.",
                "MOKE PEACE 18 CORP.",
                "MOKE PEACE 16 CORP.",
                "MOKE PEACE 43 CORP.",
                "MOKE PEACE 20 CORP.",
                "MOKE PEACE 21 CORP.",
                "MOKE PEACE 15 CORP.",
                "MOKE PEACE 17 CORP.",
                "MOKE PEACE 17 CORP",
                "MOKE PEACE CORP",
              ],
            },
            AlternateAddresses: {
              Street: "12721 LIBERTY AVE",
              City: "JAMAICA",
              State: "NY",
              ZipCode: "11419-2215",
              County: "QUEENS COUNTY",
              Country: "USA",
              Latitude: "40.688736",
              Longitude: "-73.817784",
            },
            Phones: {},
            BusinessExecutives: {
              Name: "SHAHMINA A AKTHER",
              Title: "PRINCIPAL",
            },
            ListOfDUNSNumbers: {
              DUNSNumber: "08-079-4609",
            },
            ListOfFileStates: {
              FileState: "NY",
            },
            CorporationInfo: [
              {
                CorporationNumber: "5047312",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5043130",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4963201",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5030852",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5061415",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4915430",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4864031",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5068276",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4990453",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5027795",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4684528",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "4860987",
                StateOfIncorporation: "NEW YORK",
              },
              {
                CorporationNumber: "5016712",
                StateOfIncorporation: "NEW YORK",
              },
              {
                DateIncorporated: "2017",
              },
            ],
            UCCInfo: [
              {
                UCCFilingDate: "02/17/2022",
              },
              {
                UCCFilingDate: "09/30/2021",
              },
              {
                UCCFilingDate: "09/07/2021",
              },
              {
                UCCFilingDate: "02/04/2020",
              },
              {
                UCCFilingDate: "08/31/2017",
              },
              {
                UCCFilingDate: "01/13/2017",
              },
              {
                UCCFilingDate: "01/03/2017",
              },
              {
                UCCFilingDate: "12/02/2016",
              },
              {
                UCCFilingDate: "11/23/2016",
              },
              {
                UCCFilingDate: "10/31/2016",
              },
              {
                UCCFilingDate: "10/24/2016",
              },
              {
                UCCFilingDate: "09/29/2016",
              },
              {
                UCCFilingDate: "08/09/2016",
              },
              {
                UCCFilingDate: "06/15/2016",
              },
              {
                UCCFilingDate: "03/18/2016",
              },
              {
                UCCFilingDate: "12/14/2015",
              },
              {
                UCCFilingDate: "12/08/2015",
              },
              {
                UCCFilingDate: "07/31/2015",
              },
              {
                UCCFilingDate: "12/23/2014",
              },
            ],
            Message:
              "Please Note: Limited information is available for this business. Information is included from  and Corporate Filing and Worldbase",
            CompanyEntityId: "C2__LTExMjYzMDU4NzQ1NQ",
            AllSourceDocuments: [
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I02b8ca507a2b11ec9f24ec7b211d8087",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I9485ff11b98411e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I8c4cc862b3df11e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "Ic7a16361357411e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I3033d161a3b111e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "Id1c4f531d4f911e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I8f137b61edcf11e598dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I0de41eb1a67011e598dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I2523ebc1daac11e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I8f549fd0614e11e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I68d726b09f6611e698dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I7f4d64e18f7d11e498db8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I372ed621a28311e598dc8b09b4f043e0",
              },
              {
                SourceName: "Corporate Filing",
                SourceDocumentGuid: "I82d0a803880711e698dc8b09b4f043e0",
              },
              {
                SourceName: "Worldbase",
                SourceDocumentGuid: "I84292ed0d59e11e79bef99c0ee06c731",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I172764c037c911e598dc8b09b4f043e0",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "Id6b7fe308f1f11e79bef99c0ee06c731",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "Ib92435a0917211ec9f24ec7b211d8087",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I5ca45763482711eaadfea82903531a62",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I1a2848b037c911e598dc8b09b4f043e0",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I6029f203234511ecbea4f0dc9fb69570",
              },
              {
                SourceName: "UCC",
                SourceDocumentGuid: "I34df158010d011ecbea4f0dc9fb69570",
              },
            ],
          },
        },
      },
      business_address_street: "127-21 LIBERTY AVENUE",
      business_address_city: "RICHMOND HILL",
      business_address_state: "NEW YORK",
      business_address_zip: "11419",
      source_references:
        "UCC, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Corporate Filing, Worldbase, UCC, UCC, UCC, UCC, UCC, UCC, UCC",
      incorporated_state: "NEW YORK",
      incorporated_date: null,
      source_includes_corp_filing: 1,
      business_executives: [
        {
          Name: "SHAHMINA A AKTHER",
          Title: "PRINCIPAL",
        },
      ],
    },
    business_address_street: "127-21 LIBERTY AVENUE",
    business_address_city: "RICHMOND HILL",
    business_address_state: "NEW YORK",
    business_address_zip: "11419",
  },
  {
    entity_results_page: "9b7e89da12b847259f8e6bffa2d346c3",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "9b7e89da12b847259f8e6bffa2d346c3",
    company_entity_id: "C2__LTEwOTI0MDE5MDAyNw",
    result_entity_name: "MOKE PEACE 2 CORP.",
    name_match_score: 71,
    relevance_score: 43,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "249 ST. MARK'S AVENUE",
      City: "FREEPORT",
      State: "NY",
      ZipCode: "11520",
      County: "NASSAU COUNTY",
      Country: "UNITED STATES",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
    source_references: "Corporate Filing",
    incorporated_state: "NEW YORK",
    source_includes_corp_filing: 1,
    business_executives: null,
    incorporated_date: null,
    sum_of_scores: 116,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "9b7e89da12b847259f8e6bffa2d346c3",
      company_entity_id: "C2__LTEwOTI0MDE5MDAyNw",
      pulled_business_name: "MOKE PEACE 2 CORP.",
      name_match_score: 71,
      relevance_score: 43,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "249 ST. MARK'S AVENUE",
        City: "FREEPORT",
        State: "NY",
        ZipCode: "11520",
        County: "NASSAU COUNTY",
        Country: "UNITED STATES",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
      full_result: {
        GroupId: "9b7e89da12b847259f8e6bffa2d346c3",
        RecordCount: "1",
        Relevance: "43",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 2 CORP.",
            Address: {
              Street: "249 ST. MARK'S AVENUE",
              City: "FREEPORT",
              State: "NY",
              ZipCode: "11520",
              Country: "UNITED STATES",
            },
            FileState: "NY",
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 2 CORP.",
            Address: {
              Street: "249 ST. MARK'S AVENUE",
              City: "FREEPORT",
              State: "NY",
              ZipCode: "11520",
              County: "NASSAU COUNTY",
              Country: "UNITED STATES",
            },
            Phones: {},
            ListOfFileStates: {
              FileState: "NY",
            },
            CorporationInfo: {
              CorporationNumber: "4776732",
              StateOfIncorporation: "NEW YORK",
            },
            Message:
              "Please Note: Limited information is available for this business. Information is included from Corporate Filing",
            CompanyEntityId: "C2__LTEwOTI0MDE5MDAyNw",
            AllSourceDocuments: {
              SourceName: "Corporate Filing",
              SourceDocumentGuid: "I466e5c61176d11e598db8b09b4f043e0",
            },
          },
        },
      },
      business_address_street: "249 ST. MARK'S AVENUE",
      business_address_city: "FREEPORT",
      business_address_state: "NY",
      business_address_zip: "11520",
      source_references: "Corporate Filing",
      incorporated_state: "NEW YORK",
      source_includes_corp_filing: 1,
    },
    business_address_street: "249 ST. MARK'S AVENUE",
    business_address_city: "FREEPORT",
    business_address_state: "NY",
    business_address_zip: "11520",
  },
  {
    entity_results_page: "b9a3bf5b4bfb466c9b2eced090dc6f92",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "b9a3bf5b4bfb466c9b2eced090dc6f92",
    company_entity_id: "C2__LTExNjExNTgzODA4NA",
    result_entity_name: "MOKE PEACE 2 CORP.",
    name_match_score: 71,
    relevance_score: 43,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "249 SAINT MARKS AVE",
      City: "FREEPORT",
      State: "NY",
      ZipCode: "11520-6020",
      County: "NASSAU COUNTY",
      Country: "USA",
      Latitude: "40.637075",
      Longitude: "-73.590303",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Worldbase",
    source_references: "Worldbase",
    incorporated_state: null,
    source_includes_corp_filing: 1,
    business_executives: null,
    incorporated_date: "2015",
    sum_of_scores: 116,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "b9a3bf5b4bfb466c9b2eced090dc6f92",
      company_entity_id: "C2__LTExNjExNTgzODA4NA",
      pulled_business_name: "MOKE PEACE 2 CORP.",
      name_match_score: 71,
      relevance_score: 43,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "249 SAINT MARKS AVE",
        City: "FREEPORT",
        State: "NY",
        ZipCode: "11520-6020",
        County: "NASSAU COUNTY",
        Country: "USA",
        Latitude: "40.637075",
        Longitude: "-73.590303",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Worldbase",
      full_result: {
        GroupId: "b9a3bf5b4bfb466c9b2eced090dc6f92",
        RecordCount: "1",
        Relevance: "43",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 2 CORP.",
            Address: {
              Street: "249 SAINT MARKS AVE",
              City: "FREEPORT",
              State: "NY",
              ZipCode: "11520-6020",
              Country: "USA",
            },
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 2 CORP.",
            Address: {
              Street: "249 SAINT MARKS AVE",
              City: "FREEPORT",
              State: "NY",
              ZipCode: "11520-6020",
              County: "NASSAU COUNTY",
              Country: "USA",
              Latitude: "40.637075",
              Longitude: "-73.590303",
            },
            Phones: {},
            SICDetail: {
              SICCode: "9999",
              SICDesc: "Nonclassifiable Establishments",
            },
            ListOfDUNSNumbers: {
              DUNSNumber: "04-215-0158",
            },
            ListOfFileStates: {},
            CorporationInfo: {
              DateIncorporated: "2015",
            },
            Message:
              "Please Note: Limited information is available for this business. Information is included from Worldbase",
            CompanyEntityId: "C2__LTExNjExNTgzODA4NA",
            AllSourceDocuments: {
              SourceName: "Worldbase",
              SourceDocumentGuid: "I3dca87c1ecf411eabea4f0dc9fb69570",
            },
          },
        },
      },
      business_address_street: "249 SAINT MARKS AVE",
      business_address_city: "FREEPORT",
      business_address_state: "NY",
      business_address_zip: "11520-6020",
      source_references: "Worldbase",
      incorporated_date: "2015",
      source_includes_corp_filing: 1,
    },
    business_address_street: "249 SAINT MARKS AVE",
    business_address_city: "FREEPORT",
    business_address_state: "NY",
    business_address_zip: "11520-6020",
  },
  {
    entity_results_page: "d6484fc9df2643489c7bca27306cdf78",
    searched_entity_name: "Moke Peace Peace Peace Corp",
    forecasa_data: null,
    group_id: "d6484fc9df2643489c7bca27306cdf78",
    company_entity_id: "C2__LTExNjc0MTM0NzcwOA",
    result_entity_name: "MOKE PEACE 2 CORP",
    name_match_score: 73,
    relevance_score: 43,
    count_of_sources_for_entity: 1,
    returned_business_address: {
      Street: "195 SAINT JAMES PL",
      City: "BROOKLYN",
      State: "NY",
      ZipCode: "11238-7385",
      County: "KINGS COUNTY",
      Country: "USA",
      Latitude: "40.683826",
      Longitude: "-73.963872",
    },
    returned_business_message:
      "Please Note: Limited information is available for this business. Information is included from Worldbase",
    source_references: "Worldbase",
    incorporated_state: null,
    source_includes_corp_filing: -1,
    business_executives: [
      {
        Name: "ANDY ALEGE",
        Title: "PRESIDENT",
      },
    ],
    incorporated_date: null,
    sum_of_scores: 116,
    entity_pulled: {
      searched_entity_name: "Moke Peace Peace Peace Corp",
      forecasa_data: null,
      lender: null,
      geographic_focus: null,
      pulled: "2023-01-23 19:57:53.469622",
      group_id: "d6484fc9df2643489c7bca27306cdf78",
      company_entity_id: "C2__LTExNjc0MTM0NzcwOA",
      pulled_business_name: "MOKE PEACE 2 CORP",
      name_match_score: 73,
      relevance_score: 43,
      count_of_sources_for_entity: 1,
      returned_business_address: {
        Street: "195 SAINT JAMES PL",
        City: "BROOKLYN",
        State: "NY",
        ZipCode: "11238-7385",
        County: "KINGS COUNTY",
        Country: "USA",
        Latitude: "40.683826",
        Longitude: "-73.963872",
      },
      returned_business_message:
        "Please Note: Limited information is available for this business. Information is included from Worldbase",
      full_result: {
        GroupId: "d6484fc9df2643489c7bca27306cdf78",
        RecordCount: "1",
        Relevance: "43",
        DominantValues: {
          BusinessDominantValues: {
            Name: "MOKE PEACE 2 CORP",
            Address: {
              Street: "195 SAINT JAMES PL",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11238-7385",
              Country: "USA",
            },
          },
        },
        RecordDetails: {
          BusinessResponseDetail: {
            BusinessName: "MOKE PEACE 2 CORP",
            Address: {
              Street: "195 SAINT JAMES PL",
              City: "BROOKLYN",
              State: "NY",
              ZipCode: "11238-7385",
              County: "KINGS COUNTY",
              Country: "USA",
              Latitude: "40.683826",
              Longitude: "-73.963872",
            },
            Phones: {},
            SICDetail: {
              SICCode: "9999",
              SICDesc: "Nonclassifiable Establishments",
            },
            BusinessExecutives: {
              Name: "ANDY ALEGE",
              Title: "PRESIDENT",
            },
            ListOfDUNSNumbers: {
              DUNSNumber: "11-722-2531",
            },
            ListOfFileStates: {},
            Message:
              "Please Note: Limited information is available for this business. Information is included from Worldbase",
            CompanyEntityId: "C2__LTExNjc0MTM0NzcwOA",
            AllSourceDocuments: {
              SourceName: "Worldbase",
              SourceDocumentGuid: "Ia6676db00f8311eaadfea82903531a62",
            },
          },
        },
      },
      business_address_street: "195 SAINT JAMES PL",
      business_address_city: "BROOKLYN",
      business_address_state: "NY",
      business_address_zip: "11238-7385",
      source_references: "Worldbase",
      source_includes_corp_filing: -1,
      business_executives: [
        {
          Name: "ANDY ALEGE",
          Title: "PRESIDENT",
        },
      ],
    },
    business_address_street: "195 SAINT JAMES PL",
    business_address_city: "BROOKLYN",
    business_address_state: "NY",
    business_address_zip: "11238-7385",
  },
];
