export const DUMMY_CHANGE_LOG = [
  {
    _id: "63eeb47ca327eca37974b4e6",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bf2",
      emailAddress: "ch@flatironrealtycapital.com",
      hubspot_owner_id: 81932672.0,
      firstName: "Connor",
      lastName: "Howell",
      verified: true,
      userType: "admin",
      unkownDocs: [
        "f119c6ea-3439-11ed-ade5-2f93864bad73.png",
        "624aebd0-343c-11ed-ade5-2f93864bad73.pdf",
        "ff85571e-3446-11ed-ade5-2f93864bad73.png",
        "9e98bddc-3460-11ed-ade5-2f93864bad73.png",
      ],
      noCategory: ["53f90706-3473-11ed-ade5-2f93864bad73.png"],
      appraisalPDF: [
        "a2b9c746-3477-11ed-ade5-2f93864bad73.png",
        "c035ac70-3479-11ed-ade5-2f93864bad73.jpg",
      ],
      ein: ["a2b9c748-3477-11ed-ade5-2f93864bad73.png"],
      articlesOfOrganization: ["a2b9c74a-3477-11ed-ade5-2f93864bad73.png"],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Connor Howell",
      stytch_user_id: "user-live-26af4c2f-24e6-4c41-bab7-c70cb8aa84b3",
    },
    dealId: "63b74ba3a198e91b63dd945d",
    updateTimeStamp: "2023-02-16 22:55:56.591000",
    ironId: 3117,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanProductType",
          change_summary: {
            prior_value: "30-Year Rental Loan",
            updated_value: "30 Year Investor Loan",
          },
          full_diff_summary: [
            "change",
            "loanProductType",
            ["30-Year Rental Loan", "30 Year Investor Loan"],
          ],
        },
      ],
    },
  },
  {
    _id: "63efa49ca327eca37974b4e7",
    statusChange: "appraisal_in",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "635945ba7e7e860a2d27bed9",
    updateTimeStamp: "2023-02-17 16:00:28.791000",
    ironId: 3081,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Appraisal In",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Dead",
            updated_value: "Appraisal In",
          },
          full_diff_summary: ["change", "loanStatus", ["Dead", "Appraisal In"]],
        },
      ],
    },
  },
  {
    _id: "63f39d30a327eca37974b4e8",
    statusChange: "appraisal_in",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-20 16:17:52.734000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Appraisal In",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Money In",
            updated_value: "Appraisal In",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Money In", "Appraisal In"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f3ac64a327eca37974b4e9",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-20 17:22:44.909000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Appraisal In",
            updated_value: "Underwriting",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Appraisal In", "Underwriting"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f3bc82a327eca37974b4ea",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-20 18:31:30.328000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanSubjectName",
          change_summary: {
            prior_value: "620 Brookfield Dr Hurst TX 76953",
            updated_value: "620 Brookfield Dr Hurst TX 76053",
          },
          full_diff_summary: [
            "change",
            "loanSubjectName",
            [
              "620 Brookfield Dr Hurst TX 76953",
              "620 Brookfield Dr Hurst TX 76053",
            ],
          ],
        },
      ],
    },
  },
  {
    _id: "63f3bcd4a327eca37974b4eb",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-20 18:32:52.081000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "entityName",
          change_summary: {
            prior_value: null,
            updated_value: "Kelcher Management, Inc.    ",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityName", "Kelcher Management, Inc.    "]],
          ],
        },
        {
          change_type: "add",
          object_key: "entityType",
          change_summary: {
            prior_value: null,
            updated_value: "Corporation",
          },
          full_diff_summary: ["add", "", [["entityType", "Corporation"]]],
        },
        {
          change_type: "add",
          object_key: "entityStateOfOrganization",
          change_summary: {
            prior_value: null,
            updated_value: "Texas",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityStateOfOrganization", "Texas"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63f4e7d2a327eca37974b4ec",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ebc7d6c7e606ec95105c25",
    updateTimeStamp: "2023-02-21 15:48:34.183000",
    ironId: 3143,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "New",
            updated_value: "Underwriting",
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Underwriting"]],
        },
      ],
    },
  },
  {
    _id: "63f4e7f7a327eca37974b4ed",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ebc7d6c7e606ec95105c25",
    updateTimeStamp: "2023-02-21 15:49:11.674000",
    ironId: 3143,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "loanToAsIsValue",
          change_summary: {
            prior_value: null,
            updated_value: 1975000,
          },
          full_diff_summary: ["add", "", [["loanToAsIsValue", 1975000]]],
        },
        {
          change_type: "add",
          object_key: "loanToAfterRenovationValue",
          change_summary: {
            prior_value: null,
            updated_value: 2300000,
          },
          full_diff_summary: [
            "add",
            "",
            [["loanToAfterRenovationValue", 2300000]],
          ],
        },
        {
          change_type: "add",
          object_key: "originationPoints",
          change_summary: {
            prior_value: null,
            updated_value: 2,
          },
          full_diff_summary: ["add", "", [["originationPoints", 2]]],
        },
      ],
    },
  },
  {
    _id: "63f4efb7a327eca37974b4ee",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c15",
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294.0,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
      stytch_user_id: "user-live-519af13f-11e4-4125-8af7-33351d9a464f",
    },
    dealId: "63e3d20278568dc311800f15",
    updateTimeStamp: "2023-02-21 16:22:15.183000",
    ironId: 3136,
    loanSalesperson: {
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "New",
            updated_value: "Underwriting",
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Underwriting"]],
        },
      ],
    },
  },
  {
    _id: "63f501f3a327eca37974b4ef",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-21 17:40:03.104000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "New",
            updated_value: "Underwriting",
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Underwriting"]],
        },
      ],
    },
  },
  {
    _id: "63f508a5a327eca37974b4f0",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63e3d20278568dc311800f15",
    updateTimeStamp: "2023-02-21 18:08:37.826000",
    ironId: 3136,
    loanSalesperson: {
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "entityName",
          change_summary: {
            prior_value: null,
            updated_value: "Jaxon Properties LLC ",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityName", "Jaxon Properties LLC "]],
          ],
        },
        {
          change_type: "add",
          object_key: "entityType",
          change_summary: {
            prior_value: null,
            updated_value: "LLC",
          },
          full_diff_summary: ["add", "", [["entityType", "LLC"]]],
        },
        {
          change_type: "add",
          object_key: "entityStateOfOrganization",
          change_summary: {
            prior_value: null,
            updated_value: "Pennsylvania",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityStateOfOrganization", "Pennsylvania"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63f52e50a327eca37974b4f1",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-21 20:49:20.351000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "entityStateOfOrganization",
          change_summary: {
            prior_value: null,
            updated_value: "New York",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityStateOfOrganization", "New York"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63f54e22a327eca37974b4f2",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "630e1df762975f8789d0c70c",
      emailAddress: "db@flatironrealtycapital.com",
      firstName: "Dylan",
      lastName: "Beckwith",
      phoneNumber: "5164916464",
      userType: "op",
      verified: true,
      op: {},
      unkownDocs: [null, null, null, null],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Dylan Beckwith",
      stytch_user_id: "user-live-21f0e7fc-2258-45bf-8dd8-dcf998343411",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-21 23:05:06.427000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 476900,
            updated_value: 451710,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [476900, 451710],
          ],
        },
      ],
    },
  },
  {
    _id: "63f63573a327eca37974b4f3",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-22 15:32:03.661000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 451710,
            updated_value: 280000,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [451710, 280000],
          ],
        },
        {
          change_type: "change",
          object_key: "constructionRenovationBudget",
          change_summary: {
            prior_value: 150000,
            updated_value: 171710,
          },
          full_diff_summary: [
            "change",
            "constructionRenovationBudget",
            [150000, 171710],
          ],
        },
        {
          change_type: "change",
          object_key: "closingDate",
          change_summary: {
            prior_value: "2023-03-03 16:19:52.524000",
            updated_value: "2023-02-24T16:19:52.000Z",
          },
          full_diff_summary: [
            "change",
            "closingDate",
            ["2023-03-03 16:19:52.524000", "2023-02-24T16:19:52.000Z"],
          ],
        },
        {
          change_type: "change",
          object_key: "interestRate",
          change_summary: {
            prior_value: 12.5,
            updated_value: 13,
          },
          full_diff_summary: ["change", "interestRate", [12.5, 13]],
        },
        {
          change_type: "change",
          object_key: "originationPoints",
          change_summary: {
            prior_value: 2.5,
            updated_value: 3,
          },
          full_diff_summary: ["change", "originationPoints", [2.5, 3]],
        },
      ],
    },
  },
  {
    _id: "63f638a9a327eca37974b4f4",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63b74ba3a198e91b63dd945d",
    updateTimeStamp: "2023-02-22 15:45:45.616000",
    ironId: 3117,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 267000,
            updated_value: 273000,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [267000, 273000],
          ],
        },
        {
          change_type: "change",
          object_key: "interestRate",
          change_summary: {
            prior_value: 8.875,
            updated_value: 9.375,
          },
          full_diff_summary: ["change", "interestRate", [8.875, 9.375]],
        },
        {
          change_type: "add",
          object_key: "originationPoints",
          change_summary: {
            prior_value: null,
            updated_value: 2,
          },
          full_diff_summary: ["add", "", [["originationPoints", 2]]],
        },
        {
          change_type: "add",
          object_key: "discountPoints",
          change_summary: {
            prior_value: null,
            updated_value: 1.75,
          },
          full_diff_summary: ["add", "", [["discountPoints", 1.75]]],
        },
      ],
    },
  },
  {
    _id: "63f6536ba327eca37974b4f5",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63dd62e18a7a81664ffd1f15",
    updateTimeStamp: "2023-02-22 17:39:55.121000",
    ironId: 3131,
    loanSalesperson: {
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "entityName",
          change_summary: {
            prior_value: "Villaagave LLC",
            updated_value: "Villa577 LLC",
          },
          full_diff_summary: [
            "change",
            "entityName",
            ["Villaagave LLC", "Villa577 LLC"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f65374a327eca37974b4f6",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63dd62e18a7a81664ffd1f15",
    updateTimeStamp: "2023-02-22 17:40:04.548000",
    ironId: 3131,
    loanSalesperson: {
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "entityOrganizationDate",
          change_summary: {
            prior_value: null,
            updated_value: "2023-02-14T05:00:00.000Z",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityOrganizationDate", "2023-02-14T05:00:00.000Z"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63f77781a327eca37974b4f7",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c12",
      emailAddress: "st@flatironrealtycapital.com",
      hubspot_owner_id: 50209327.0,
      firstName: "Seena",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Seena Talas",
      stytch_user_id: "user-live-db1ec0b5-1d01-44c5-9fb0-9394264568e5",
    },
    dealId: "63dd62e18a7a81664ffd1f15",
    updateTimeStamp: "2023-02-23 14:26:09.593000",
    ironId: 3131,
    loanSalesperson: {
      emailAddress: "zf@flatironrealtycapital.com",
      hubspot_owner_id: 119969294,
      firstName: "Zakary",
      lastName: "Fouladi",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Zakary Fouladi",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanProductType",
          change_summary: {
            prior_value: "Stabilized Bridge",
            updated_value: "30 Year Investor Loan",
          },
          full_diff_summary: [
            "change",
            "loanProductType",
            ["Stabilized Bridge", "30 Year Investor Loan"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f78b2ea327eca37974b4f8",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63eaac97c7e606ec95105be5",
    updateTimeStamp: "2023-02-23 15:50:06.396000",
    ironId: 3140,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Money In",
            updated_value: "Underwriting",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Money In", "Underwriting"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f78da3a327eca37974b4f9",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-23 16:00:35.681000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 280000,
            updated_value: 451710,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [280000, 451710],
          ],
        },
      ],
    },
  },
  {
    _id: "63f7ac56a327eca37974b4fa",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63eaac97c7e606ec95105be5",
    updateTimeStamp: "2023-02-23 18:11:34.138000",
    ironId: 3140,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "entityName",
          change_summary: {
            prior_value: null,
            updated_value: "Treehouse 323 LLC ",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityName", "Treehouse 323 LLC "]],
          ],
        },
        {
          change_type: "add",
          object_key: "entityStateOfOrganization",
          change_summary: {
            prior_value: null,
            updated_value: "Florida",
          },
          full_diff_summary: [
            "add",
            "",
            [["entityStateOfOrganization", "Florida"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63f7b3e6a327eca37974b4fb",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63eaac97c7e606ec95105be5",
    updateTimeStamp: "2023-02-23 18:43:50.751000",
    ironId: 3140,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanSubjectName",
          change_summary: {
            prior_value: "790 NE 77th Terrace Miami FL 33138",
            updated_value: "790 NE 77th Ter Miami FL 33138",
          },
          full_diff_summary: [
            "change",
            "loanSubjectName",
            [
              "790 NE 77th Terrace Miami FL 33138",
              "790 NE 77th Ter Miami FL 33138",
            ],
          ],
        },
      ],
    },
  },
  {
    _id: "63f8c9cca327eca37974b4fc",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-24 14:29:32.463000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 451710,
            updated_value: 434539,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [451710, 434539],
          ],
        },
      ],
    },
  },
  {
    _id: "63f9047fa327eca37974b4fd",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-24 18:39:59.812000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanProductType",
          change_summary: {
            prior_value: "30-Year Rental Loan",
            updated_value: "30 Year Investor Loan",
          },
          full_diff_summary: [
            "change",
            "loanProductType",
            ["30-Year Rental Loan", "30 Year Investor Loan"],
          ],
        },
      ],
    },
  },
  {
    _id: "63f920f3a327eca37974b4fe",
    statusChange: "closed",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63b74ba3a198e91b63dd945d",
    updateTimeStamp: "2023-02-24 20:41:23.175000",
    ironId: 3117,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Closed w/Stips",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Closed w/Stips",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Underwriting", "Closed w/Stips"],
          ],
        },
      ],
    },
  },
  {
    _id: "63fa2f0ca327eca37974b4ff",
    statusChange: "appraisal_in",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e115fa8a7a81664ffd1f20",
    updateTimeStamp: "2023-02-25 15:53:48.758000",
    ironId: 3132,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Appraisal In",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Money In",
            updated_value: "Appraisal In",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Money In", "Appraisal In"],
          ],
        },
      ],
    },
  },
  {
    _id: "63fa3838a327eca37974b500",
    statusChange: "closed",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ea4caac7e606ec95105bb9",
    updateTimeStamp: "2023-02-25 16:32:56.320000",
    ironId: 3139,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Closed",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Closed",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Underwriting", "Closed"],
          ],
        },
      ],
    },
  },
  {
    _id: "63fd3058a327eca37974b501",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-27 22:36:04.990000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 195000,
            updated_value: 156200,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [195000, 156200],
          ],
        },
        {
          change_type: "add",
          object_key: "originationPoints",
          change_summary: {
            prior_value: null,
            updated_value: 1.75,
          },
          full_diff_summary: ["add", "", [["originationPoints", 1.75]]],
        },
        {
          change_type: "add",
          object_key: "discountPoints",
          change_summary: {
            prior_value: null,
            updated_value: 250,
          },
          full_diff_summary: ["add", "", [["discountPoints", 250]]],
        },
      ],
    },
  },
  {
    _id: "63fd3067a327eca37974b502",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-02-27 22:36:23.599000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "discountPoints",
          change_summary: {
            prior_value: 250,
            updated_value: 2.5,
          },
          full_diff_summary: ["change", "discountPoints", [250, 2.5]],
        },
      ],
    },
  },
  {
    _id: "63fd3682a327eca37974b503",
    statusChange: "closed",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63ebc7d6c7e606ec95105c25",
    updateTimeStamp: "2023-02-27 23:02:26.863000",
    ironId: 3143,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Closed",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Closed",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Underwriting", "Closed"],
          ],
        },
      ],
    },
  },
  {
    _id: "63fd368ea327eca37974b504",
    statusChange: "closed",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63e53618bd20717fdb668d7d",
    updateTimeStamp: "2023-02-27 23:02:38.905000",
    ironId: 3138,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Closed",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Closed",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Underwriting", "Closed"],
          ],
        },
      ],
    },
  },
  {
    _id: "63fe5e49a327eca37974b505",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c13",
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486.0,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
      stytch_user_id: "user-live-600253d8-5bd0-4221-82f0-1dba6ed4b847",
    },
    dealId: "63d941958a7a81664ffd1e91",
    updateTimeStamp: "2023-02-28 20:04:25.490000",
    ironId: 3128,
    loanSalesperson: {
      emailAddress: "stalas@flatironrealtycapital.com",
      hubspot_owner_id: 160692486,
      firstName: "Sep",
      lastName: "Talas",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Sep Talas",
    },
    loanStatus: "Dead",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "New",
            updated_value: "Dead",
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Dead"]],
        },
      ],
    },
  },
  {
    _id: "63fe69fda327eca37974b506",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63b44fb4441de07a4923615d",
    updateTimeStamp: "2023-02-28 20:54:21.842000",
    ironId: 3111,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Dead",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Dead",
          },
          full_diff_summary: ["change", "loanStatus", ["Underwriting", "Dead"]],
        },
      ],
    },
  },
  {
    _id: "63fe71dea327eca37974b507",
    statusChange: "money_in",
    updateType: "underwriting_notes",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63fe71cac7e606ec95105e0a",
    updateTimeStamp: "2023-02-28 21:27:58.729000",
    ironId: 3147,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Money In",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: `"{"blocks":[{"key":"t0fa","text":"Example notes","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"aj42u","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"88vv2","text":"new example2","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"aghuf","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"3f9c8","text":"Test saveseefeffft","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":7,"length":11,"style":"RED"}],"entityRanges":[],"data":{}},{"key":"fnrio","text":"testsssss","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":9,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"aj2vq","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"bug2t","text":"sdasd","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":5,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"eg2ne","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"e6trj","text":"sdasdasd","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":8,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"dk4v8","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"5cm26","text":"prod testsssssss","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":16,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"9tih3","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"59pp","text":"vvvvvssss","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":9,"style":"BOLD"}],"entityRanges":[],"data":{}}],"entityMap":{}}"`,
            updated_value:
              '"{"blocks":[{"key":"t0fa","text":"Example notes","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"aj42u","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"88vv2","text":"new example2","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"aghuf","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"3f9c8","text":"Test saveseefeffft","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":7,"length":11,"style":"RED"}],"entityRanges":[],"data":{}},{"key":"fnrio","text":"testsssss","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":9,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"aj2vq","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"bug2t","text":"sdasd","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":5,"style":"BOLD"}],"',
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Money In"]],
        },
      ],
    },
  },
  {
    _id: "63ff379ca327eca37974b508",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bf0",
      emailAddress: "cw@flatironrealtycapital.com",
      hubspot_owner_id: 81932675.0,
      firstName: "Christopher",
      lastName: "Wolpert",
      verified: true,
      userType: "admin",
      unkownDocs: ["8a6fd994-33a2-11ed-ade5-2f93864bad73.png"],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Christopher Wolpert",
      stytch_user_id: "user-live-53bcca5a-d657-4506-8cee-39abd419fa74",
    },
    dealId: "63e52b5bbd20717fdb668d7c",
    updateTimeStamp: "2023-03-01 11:31:37.707000",
    ironId: 3137,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanPurpose",
          change_summary: {
            prior_value: "Purchase",
            updated_value: "Refinance - Cash Out",
          },
          full_diff_summary: [
            "change",
            "loanPurpose",
            ["Purchase", "Refinance - Cash Out"],
          ],
        },
      ],
    },
  },
  {
    _id: "63ff37b9a327eca37974b509",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bf0",
      emailAddress: "cw@flatironrealtycapital.com",
      hubspot_owner_id: 81932675.0,
      firstName: "Christopher",
      lastName: "Wolpert",
      verified: true,
      userType: "admin",
      unkownDocs: ["8a6fd994-33a2-11ed-ade5-2f93864bad73.png"],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Christopher Wolpert",
      stytch_user_id: "user-live-53bcca5a-d657-4506-8cee-39abd419fa74",
    },
    dealId: "63e52b5bbd20717fdb668d7c",
    updateTimeStamp: "2023-03-01 11:32:09.125000",
    ironId: 3137,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "add",
          object_key: "hubspotPipeline",
          change_summary: {
            prior_value: null,
            updated_value: "FIRC Pipeline",
          },
          full_diff_summary: [
            "add",
            "",
            [["hubspotPipeline", "FIRC Pipeline"]],
          ],
        },
      ],
    },
  },
  {
    _id: "63ff37d5a327eca37974b50a",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bf0",
      emailAddress: "cw@flatironrealtycapital.com",
      hubspot_owner_id: 81932675.0,
      firstName: "Christopher",
      lastName: "Wolpert",
      verified: true,
      userType: "admin",
      unkownDocs: ["8a6fd994-33a2-11ed-ade5-2f93864bad73.png"],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Christopher Wolpert",
      stytch_user_id: "user-live-53bcca5a-d657-4506-8cee-39abd419fa74",
    },
    dealId: "63e52b5bbd20717fdb668d7c",
    updateTimeStamp: "2023-03-01 11:32:37.884000",
    ironId: 3137,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "hubspotPipeline",
          change_summary: {
            prior_value: "FIRC Pipeline",
            updated_value: "TPO Deals Pipeline",
          },
          full_diff_summary: [
            "change",
            "hubspotPipeline",
            ["FIRC Pipeline", "TPO Deals Pipeline"],
          ],
        },
      ],
    },
  },
  {
    _id: "63ff48e1a327eca37974b50b",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bf0",
      emailAddress: "cw@flatironrealtycapital.com",
      hubspot_owner_id: 81932675.0,
      firstName: "Christopher",
      lastName: "Wolpert",
      verified: true,
      userType: "admin",
      unkownDocs: ["8a6fd994-33a2-11ed-ade5-2f93864bad73.png"],
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Christopher Wolpert",
      stytch_user_id: "user-live-53bcca5a-d657-4506-8cee-39abd419fa74",
    },
    dealId: "63e52b5bbd20717fdb668d7c",
    updateTimeStamp: "2023-03-01 12:45:21.838000",
    ironId: 3137,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 66666,
            updated_value: 66000,
          },
          full_diff_summary: ["change", "requestedLoanAmount", [66666, 66000]],
        },
      ],
    },
  },
  {
    _id: "63ffa77fa327eca37974b50c",
    statusChange: "money_in",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36bea",
      emailAddress: "arr@flatironrealtycapital.com",
      hubspot_owner_id: 51265180.0,
      firstName: "Ariel",
      lastName: "Rayhanian",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Ariel Rayhanian",
      stytch_user_id: "user-live-43922bd5-76cc-47c3-af91-f87d9b769bc2",
    },
    dealId: "63ffa6ffc7e606ec95105e27",
    updateTimeStamp: "2023-03-01 19:29:03.385000",
    ironId: 3149,
    loanSalesperson: {
      emailAddress: "arr@flatironrealtycapital.com",
      hubspot_owner_id: 51265180,
      firstName: "Ariel",
      lastName: "Rayhanian",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Ariel Rayhanian",
    },
    loanStatus: "Money In",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "New",
            updated_value: "Money In",
          },
          full_diff_summary: ["change", "loanStatus", ["New", "Money In"]],
        },
      ],
    },
  },
  {
    _id: "63ffb6f4a327eca37974b50d",
    statusChange: "underwriting",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c10",
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236.0,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
      stytch_user_id: "user-live-f64ec035-c61f-41b6-9a6b-9aace115cd55",
    },
    dealId: "63b74db8a198e91b63dd945f",
    updateTimeStamp: "2023-03-01 20:35:00.520000",
    ironId: 3118,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Underwriting",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Dead",
            updated_value: "Underwriting",
          },
          full_diff_summary: ["change", "loanStatus", ["Dead", "Underwriting"]],
        },
      ],
    },
  },
  {
    _id: "63ffc2cea327eca37974b50e",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "63249977868e7b9a1d2253bf",
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      phoneNumber: "6314563373",
      formType: "creditAuth",
      userType: "admin",
      verified: true,
      borrower: {},
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
      stytch_user_id: "user-live-480ba57f-6cc6-485f-b959-7ba6cc67114d",
    },
    dealId: "63407f0eac988af75502e60f",
    updateTimeStamp: "2023-03-01 21:25:34.582000",
    ironId: 3058,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 6500594,
            updated_value: 650059,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [6500594, 650059],
          ],
        },
      ],
    },
  },
  {
    _id: "63ffc799a327eca37974b50f",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "63249977868e7b9a1d2253bf",
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      phoneNumber: "6314563373",
      formType: "creditAuth",
      userType: "admin",
      verified: true,
      borrower: {},
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
      stytch_user_id: "user-live-480ba57f-6cc6-485f-b959-7ba6cc67114d",
    },
    dealId: "63407f0eac988af75502e60f",
    updateTimeStamp: "2023-03-01 21:46:01.572000",
    ironId: 3058,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 650059,
            updated_value: 6500594,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [650059, 6500594],
          ],
        },
      ],
    },
  },
  {
    _id: "6400e03da327eca37974b510",
    statusChange: "",
    updateType: "deal_data",
    submittedBy: {
      _id: "63249977868e7b9a1d2253bf",
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      phoneNumber: "6314563373",
      formType: "creditAuth",
      userType: "admin",
      verified: true,
      borrower: {},
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
      stytch_user_id: "user-live-480ba57f-6cc6-485f-b959-7ba6cc67114d",
    },
    dealId: "63407f0eac988af75502e60f",
    updateTimeStamp: "2023-03-02 17:43:24.276000",
    ironId: 3058,
    loanSalesperson: {
      firstName: "James",
      lastName: "Oliva",
      emailAddress: "jo@flatironrealtycapital.com",
      userType: "admin",
      verified: true,
      isActiveUser: true,
      isInternalUser: true,
      fullName: "James Oliva",
    },
    loanStatus: {},
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "requestedLoanAmount",
          change_summary: {
            prior_value: 6500594,
            updated_value: 6200000,
          },
          full_diff_summary: [
            "change",
            "requestedLoanAmount",
            [6500594, 6200000],
          ],
        },
        {
          change_type: "add",
          object_key: "AsIsAppraisedVal",
          change_summary: {
            prior_value: null,
            updated_value: 6000000,
          },
          full_diff_summary: ["add", "", [["AsIsAppraisedVal", 6000000]]],
        },
      ],
    },
  },
  {
    _id: "6400f947a327eca37974b511",
    statusChange: "closed",
    updateType: "deal_data",
    submittedBy: {
      _id: "6312307975c143b35cf36c16",
      emailAddress: "ah@flatironrealtycapital.com",
      hubspot_owner_id: null,
      firstName: "Amy",
      lastName: "Ho",
      verified: true,
      userType: "underwriter",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Amy Ho",
      stytch_user_id: "user-live-0848e335-0b83-4709-8065-e0d9f2fe029d",
    },
    dealId: "63e2b9bb8a7a81664ffd1f66",
    updateTimeStamp: "2023-03-02 19:30:15.382000",
    ironId: 3133,
    loanSalesperson: {
      emailAddress: "sh@flatironrealtycapital.com",
      hubspot_owner_id: 50639236,
      firstName: "Samuel",
      lastName: "Huang",
      verified: true,
      userType: "loanOfficer",
      isActiveUser: true,
      isInternalUser: true,
      fullName: "Samuel Huang",
    },
    loanStatus: "Closed w/Stips",
    updateSummary: {
      dealUpdates: [
        {
          change_type: "change",
          object_key: "loanStatus",
          change_summary: {
            prior_value: "Underwriting",
            updated_value: "Closed w/Stips",
          },
          full_diff_summary: [
            "change",
            "loanStatus",
            ["Underwriting", "Closed w/Stips"],
          ],
        },
      ],
    },
  },
];
