export const DUMMY_LOAN_APP = {
  firstName: "James",
  lastName: "Oliva",
  emailAddress: "olivajames110@gmail.com",
  phoneNumber: "(631) 456-3373",
  ssn: "234",
  primaryAddress: {
    address: {
      streetNumber: "125",
      streetName: "Carleon Avenue",
      city: "Larchmont",
      state: "NY",
      country: "USA",
      zip: "10538",
      fullAddress: "125 Carleon Avenue, Larchmont NY 10538",
    },
  },
  dobMonth: "September",
  dobYear: "234",
  dobDay: 34,
  citizenshipStatus: "Foreign National with SSN",
  isMarried: "false",
  estimatedCreditScore: "720-739",
  hasAdditionalGuarantors: "Yes",
  guarantors: [
    {
      firstName: "Bill",
      lastName: "Smith",
      phoneNumber: "234",
      emailAddress: "olivajames110@gmail.com",
      additionalGuarantorIsExperienced: "No",
      estimatedCreditScore: "680-699 ",
      percentageEntityOwnership: "23",
    },
    {
      firstName: "John",
      lastName: "Oliva",
      phoneNumber: "234",
      emailAddress: "olivajames110@gmail.com",
      additionalGuarantorIsExperienced: "No",
      estimatedCreditScore: "680-699 ",
      percentageEntityOwnership: "23",
    },
    {
      firstName: "Chris",
      lastName: "Cafiero",
      phoneNumber: "234",
      emailAddress: "olivajames110@gmail.com",
      additionalGuarantorIsExperienced: "No",
      estimatedCreditScore: "680-699 ",
      percentageEntityOwnership: "23",
    },
  ],
  yearsExperienceProducingProperties: 3,
  numberOfPropertiesOwnedInLastThreeYears: 3,
  groundUpConstructionProjectsInLastThreeYears: 3,
  flipsInLastThreeYears: 3,
  initialLoanAmount: 300000,
  liquidityPersonalBankAccounts: 23,
  liquidityIraBrokerageAccounts: 234,
  liquidityBusinessBankAccounts: 234,
  liquidityCashValueOfLifeInsurance: 234,
  liquidityOther: 234,
  hasDerogatoryHousingEvents: "false",
  hasBeenConvictedOfFelony: "false",
  hasTaxLiens: "No",
  hasJudgementsAmount: 234,
  hasJudgements: "Yes",
  hasChargeOffs: "No",
  loanProductType: "Stabilized Bridge",
  loanPurpose: "Purchase",
  loanPropertyHasMoreThanFourUnits: "false",
  applicationIsForMultipleProperties: "Single",
  numberOfSubjectProperties: 2,
  totalFinancedBudget: 34234,
  requestedLoanTerm: "12-month w/ 6-month extension",
  loanExitStrategy: "Sell the property",
  businessPlanDescription:
    "ease briefly describe your business plan for this loanease briefly describe your business plan for this loan",
  rehabWorkRequiredIsLight:
    "Heavy - Rehab greater than 35% of the value of the home",
  rehabPlansAreApproved: "false",
  doesPlanToFinanceFullRenovationCost: "No",
  plansForPropertyWillResultInChangeOfUse: "Yes",
  knownEnviornmentalConditionsDoExist: "Yes",
  outstandingPermitsOrViolationsDoExist: "Yes",
  rehabWorkRequiredIsLightAdditionalInfo: [
    "Addition of 750 or more square feet",
    "another",
  ],
  subjectProperties: [
    {
      units: [
        {
          unitOccupied: "No",
          unitMonthlyMarketRent: 323,
          unitMonthlyInPlaceRent: 23,
          expectedStabilizedRent: 232,
          leaseType: "Month-to-Month",
          leaseBeginDate: "2022-12-30T05:00:00.000Z",
          leasEndDate: "2022-12-22T05:00:00.000Z",
          unitLeaseDocs: ["d522a842-171a-4e1d-bd49-1bd1b6068c0c"],
        },
      ],
      address: {
        streetNumber: "125",
        streetName: "Carley Avenue",
        city: "Huntington",
        state: "NY",
        country: "USA",
        zip: "11743",
        fullAddress: "125 Carley Avenue, Huntington NY 11743",
      },
      isSelfManagingProperty: "No",
      propertyType: "Mixed-Use",
      propertyWillBeVacant: "No",
      purchasePrice: 4456,
      asIsValue: 456,
      squareFootage: 4,
      purchaseDate: "2022-12-02T05:00:00.000Z",
      annualPropertyTaxes: 345,
      annualPropertyInsurance: 345,
      hasAdditionalPropertyOrInsuranceFees: "No",
      numberOfUnits: 1,
    },
  ],
  hasWorkedWithFlatironInPast: "false",
  documents: [
    {
      file: {
        path: "bank-statement.png",
        preview:
          "blob:http://localhost:3000/456ae711-4fbc-4061-8ff1-cf5ea9803556",
      },
      id: "d522a842-171a-4e1d-bd49-1bd1b6068c0c",
      name: "subjectProperties[0].units[0].unitLeaseDocs",
      docGroup: "leasesAndRents",
      docType: "unitLeaseDocs",
      dateSubmitted: "12/08/2022",
    },
  ],
  requestedLoanAmount: 234,

  hasTaxLienAmount: 34,
  hasTaxLiensPaymentPlan: "Yes",

  hasJudgementsPaymentPlan: "Yes",

  hasChargeOffsAmount: 345,
  hasChargeOffsPaymentPlan: "Yes",
};
